### ISSUE TITLE
The plugin says it is out of date.

### ISSUE THREAD

**Issue by Inf1n1ty202** [Shin1gamiX/VoidChest#15]
**Description of issue:** 
Even though the plugin is on the latest version that is public on spigot, it still says it is out of date. 

https://prnt.sc/7C1orZaJQw4y

**VoidChest Version (using`/version voidchest`):** 1.15.2

**Server Version (using `/ver`):** 1.20.1

**Comment by Inf1n1ty202** [comment]
**Update:** Bug persists after updating to voidchest 1.16.0

**Comment by Shin1gamiX** [comment]
The screenshot you sent says it's up to date, not out of date.
