### ISSUE TITLE
VoidChest's mode doesn't load automatically and needs a second reload through the command.

### ISSUE THREAD

**Issue by Shin1gamiX** [Shin1gamiX/VoidChest#2]
Whenever I restart the server, voidchest mode is being set to default (voidchest) but I have set it to shopguiplus in options.yml. After the server loads and I do /voidchest reload, it then fixes.

Mode should be set to shopguiplus after the restart, automatically.

VoidChest version: 1.0.1 (latest)

**Comment by Cod1ngBugz** [comment]
This is most likely due to how load order is handled. Many plugins depend on each other and this messes with the load order which leads to voidchest being loaded first, unable to find shopguiplus as an enabled plugin since it is loaded afterwards.
